#!/bin/bash -ex

export DEPS=( postgres:15-alpine nginx:alpine odoo:18 )

# clean up build fs
fs_cleanup() {
  mount -l -t fuse.fuse-overlayfs | cut -d " " -f3 | xargs -rL1 fusermount -u || true
  umount -vRf /sys || true
  rm -f /dev/fuse
}

cache_images() {
  # umount everything if build fails; otherwise `deck -D` won't work!
  trap fs_cleanup INT TERM EXIT

  # podman requires sysfs & cgroups & fuse for fuse-overlayfs
  mount -t sysfs sysfs /sys -o ro,nosuid,nodev,noexec,relatime
  mkdir -p /sys/fs/{cgroup,fuse/connections}
  mount -t cgroup2 cgroup2 /sys/fs/cgroup -o rw,nosuid,nodev,noexec,relatime
  mount -t fusectl fusectl /sys/fs/fuse/connections -o rw,nosuid,nodev,noexec,relatime
  mknod /dev/fuse -m 0666 c 10 229 || true

  [[ "$FAB_HTTP_PROXY" ]] && export HTTP_PROXY="$FAB_HTTP_PROXY"

  local name
  for i in "${DEPS[@]}"; do
    name="$(basename "$i" | cut -d':' -f1)"

    podman pull "docker.io/$i"
    podman save --format oci-dir -o "/var/cache/podman-images/$name" "$i"
  done

  unset HTTP_PROXY

  podman system reset -f
}

cache_images
