#!/bin/bash -e
# regenerate odoo pgsql password

. /etc/default/inithooks

CONF=/etc/odoo/odoo.conf
DB_USER=odoo

# Create new password
DB_PASS=$(mcookie)

# Set the new password without placing it in process arguments.
printf 'db_password=%s\n' "$DB_PASS" | odoo-set-config-secrets "$CONF"

# Update the PostgreSQL role without exposing the generated password in argv.
su postgres -c 'psql --set ON_ERROR_STOP=on postgres' <<EOF
ALTER ROLE $DB_USER WITH PASSWORD '$DB_PASS';
EOF

# Since we reset the password, reload Odoo
# Don't use systemd/systemctl right now as lxc/ovz does not
# use systemd
service odoo restart

# Webserver will error if postgresql is not restarted
service postgresql restart
