#!/bin/bash -ex
# generate DB secrets

. /etc/default/inithooks

[ -e "$INITHOOKS_CONF" ] && . "$INITHOOKS_CONF"

SRC="/etc/turnkey-podman/.env.template"
DST="/etc/turnkey-podman/.env"

DB_NAME="$(mcookie)"
DB_USER="$(mcookie)"
DB_PASS="$(mcookie)"

export DB_NAME DB_USER DB_PASS
envsubst < "$SRC" > "$DST"
